import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider, useUser } from "@clerk/nextjs";
import LeftSideBar from "@/components/layout/LeftSideBar";
import MainContent from "@/components/layout/MainContent";
import RightSideBar from "@/components/layout/RightSideBar";
import { Suspense } from "react";

import { LeftSideBarSkeleton } from "@/components/ui/skeletons";
import BottomBar from "@/components/layout/BottomBar";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Socialize",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className=" flex flex-row justify-center h-full bg-dark ">
            <Suspense fallback={<LeftSideBarSkeleton />}>
              <LeftSideBar />
            </Suspense>
            <MainContent>{children}</MainContent>
            <RightSideBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
