import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LeftSideBar from "@/components/layout/LeftSideBar";
import MainContent from "@/components/layout/MainContent";
import RightSideBar from "@/components/layout/RightSideBar";

import BottomBar from "@/components/layout/BottomBar";
import Wrapper from "@/components/layout/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Socialize",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Wrapper>
      <html lang="en">
        <body className={inter.className}>
          <main className=" flex flex-row justify-center h-full bg-dark ">
            <LeftSideBar />

            <MainContent>{children}</MainContent>
            <RightSideBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </Wrapper>
  );
}
