import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "../globals.css";
import LeftSideBar from "@/components/layout/LeftSideBar";
import MainContent from "@/components/layout/MainContent";
import RightSideBar from "@/components/layout/RightSideBar";

import Wrapper from "@/components/layout/Wrapper";
import BottomBar from "@/components/layout/BottomBar";

import { disableReactDevTools } from "@fvilers/disable-react-devtools";

disableReactDevTools();

const inter = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Socialize",
  description: "Generated by create next app",
  icons: {
    icon: "/letter-s.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <main className=" flex flex-row h-full bg-black justify-center ">
            <LeftSideBar />
            <MainContent>{children}</MainContent>
            <RightSideBar />
          </main>
          <BottomBar />
        </Wrapper>
      </body>
    </html>
  );
}
